:PROPERTIES:
:ID:       c24d14e0-72b4-452c-82d7-3965162e2810
:END:
#+title: QubesOS Disposable Qube Leftovers

Qubes OS introduces the concept of Disposable VMs - Virtual machines which are immedately shutdown and "deleted" from the system when no more GUI applications are running. While it is true that the VMs themselves are deleted, there are still indicators that the virtual machine existed. For some, this may be acceptable and can be considered part of security through obscurity - By overwhelming analysts with as much information as possible. However, while these files generally do not contain sensitive information in their own right, certain information (such as log file timestamps) can be potentially used as circumstantial evidence that works in tandem with other evidence to corrolate the user to an activity. Hence, one may want to reduce traces of these files as much as possible so as to make corrolation more difficult.

** Finding Disposable VM Leftovers

To find the files generated by Disposable VMs, the following command was executed in Dom0:

#+BEGIN_SRC shell
  $ sudo find / -name '*disp[0-9]*'
#+END_SRC

The following files were identified for deleted Disposable VMs that persist a host system restart (assuming the Disposable VM's name was "dispXXXX" ("Y" representing a sequence of arbitrary numbers):

#+BEGIN_SRC
  /var/log/xen/console/guest-dispXXXX.log
  /var/log/xen/console/guest-dispXXXX.log-YYYYYYYY
  /var/log/qubes/qubesdb.dispXXXX.log
  /var/log/qubes/vm-dispXXXX.log
  /var/log/qubes/vm-dispXXXX.log-YYYYYYYY
  /var/log/qubes/qrexec.dispXXXX.log
  /var/log/qubes/pacat.dispXXXX.log
  /var/log/qubes/guid.dispXXXX.log
  /var/log/libvirt/libxl/dispXXXX.log
#+END_SRC

** File contents

This section is to document the contents of some of these files for reference.

/var/log/qubes/qubesdb.dispXXXX.log
#+BEGIN_SRC
  vchan closed
  reconnecting
  vchan closed
#+END_SRC

/var/logs/qubes/qrexec.dispXXXX.log
#+BEGIN_SRC
  eintr
  eintr
  entir
  libvchan_is_eof
#+END_SRC

